from .Candidato import *
from .Cargo import *
from .Eleccion import *
from .JuradoElectoral import *
from .Mesa import *
from .Papeleta import *
from .PartidoPolitico import *
from .Recinto import *
from .Seccion import *
from .TipoEleccion import *
from .VotanteMesa import *
