from .candidatos_view import *
from .cargos_view import *
from .elecciones_view import *
from .jurados_view import *
from .mesas_view import *
from .papeletas_view import *
from .partidos_view import *
from .recintos_view import *
from .tipo_eleccion_view import *
