# Generated by Django 5.2.4 on 2025-07-11 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('votante_id', models.UUIDField()),
                ('mesa_id', models.IntegerField()),
                ('candidato_id', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('valido', 'Válido'), ('nulo', 'Nulo')], default='valido', max_length=10)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('votante_id',)},
            },
        ),
    ]
