# Generated by Django 5.2.4 on 2025-07-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('geometria', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.cargo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.partidopolitico')),
            ],
        ),
        migrations.CreateModel(
            name='JuradoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.mesa')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='elecciones.recinto'),
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generada_automaticamente', models.BooleanField(default=True)),
                ('candidatos', models.ManyToManyField(to='elecciones.candidato')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='secciones',
            field=models.ManyToManyField(to='elecciones.seccion'),
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('secciones', models.ManyToManyField(to='elecciones.seccion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elecciones.tipoeleccion')),
            ],
        ),
        migrations.CreateModel(
            name='VotanteMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votante_uuid', models.UUIDField()),
                ('nombre_completo', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='elecciones.mesa')),
            ],
            options={
                'unique_together': {('votante_uuid', 'mesa')},
            },
        ),
    ]
